trigger: none
pool: DevopsAgent
steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: "latest"
  - task: TerraformTaskV4@4
    inputs:
      provider: "azurerm"
      command: "init"
      workingDirectory: "$(System.DefaultWorkingDirectory)/core-infra-1"
      backendServiceArm: "serviceprincipalname"
      backendAzureRmResourceGroupName: "tfstate"
      backendAzureRmStorageAccountName: "tfstateazureterraform"
      backendAzureRmContainerName: "tfstate"
      backendAzureRmKey: "terraform.tfstate"
  - task: TerraformTaskV4@4
    inputs:
      provider: "azurerm"
      command: "plan"
      workingDirectory: "$(System.DefaultWorkingDirectory)/core-infra-1"
      commandOptions: "-var-file ../ENV/core-infra-1.tfvars"
      environmentServiceNameAzureRM: "serviceprincipalname"

  - task: TerraformTaskV4@4
    inputs:
      provider: "azurerm"
      command: "apply"
      workingDirectory: "$(System.DefaultWorkingDirectory)/core-infra-1"
      commandOptions: "-var-file ../ENV/core-infra-1.tfvars"
      environmentServiceNameAzureRM: "serviceprincipalname"
